### ISSUE TITLE
Get-UsnJournalEntry does not return anything on a non OS drive

### ISSUE THREAD

**Issue by smkuls** [proxb/PoshUSNJournal#6]
I created a new journal on a non OS drive using a New-UsnJournal command.

Deleted a file on the drive.

Tried to do a Get-UsnJournalEntry and it did not return any results. 

and I get **WARNING: Issue occurred reading Usn entries!**

Get-UsnJournal entry works on the OS drive though.

I tried the same on a different non OS drive as well, same thing happens.

**Comment by proxb** [comment]
Weird. I'm able to reproduce this issue. I'll try to dig around and see if i can figure something out with this.

**Comment by proxb** [comment]
I finally found the issue and made some updates to the helper functions. I tested this on a few non-os drives and it is working as expected.
